<?xml version="1.0" encoding="utf-8"?><Database Name="ANSLMS" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NATHANIEL;Initial Catalog=ANSLMS;Integrated Security=True" SettingsObjectName="ANS_Library_Management_System.Properties.Settings" SettingsPropertyName="ANSLMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblAdminActionReport" Member="tblAdminActionReports">
    <Type Name="tblAdminActionReport">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tblAdminDetail_tblAdminActionReport" Member="tblAdminDetail" ThisKey="username" OtherKey="AdminUsername" Type="tblAdminDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUserLoginReport" Member="tblUserLoginReports">
    <Type Name="tblUserLoginReport">
      <Column Name="LoginID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tblUserDetail_tblUserLoginReport" Member="tblUserDetail" ThisKey="username" OtherKey="UserUsername" Type="tblUserDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblAdminDetails" Member="tblAdminDetails">
    <Type Name="tblAdminDetail">
      <Column Name="GenID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email_Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Question" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Answer" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tblAdminDetail_tblAdminActionReport" Member="tblAdminActionReports" ThisKey="AdminUsername" OtherKey="username" Type="tblAdminActionReport" />
      <Association Name="tblAdminDetail_tblAdminLoginReport" Member="tblAdminLoginReports" ThisKey="AdminUsername" OtherKey="username" Type="tblAdminLoginReport" />
      <Association Name="tblAdminDetail_tblAdminTransaction" Member="tblAdminTransactions" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblAdminTransaction" />
      <Association Name="tblAdminDetail_tblBookAccounting" Member="tblBookAccountings" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblBookAccounting" />
      <Association Name="tblAdminDetail_tblBook" Member="tblBooks" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblBook" />
      <Association Name="tblAdminDetail_tblBooksBorrowed" Member="tblBooksBorroweds" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblBooksBorrowed" />
      <Association Name="tblAdminDetail_tblLoginReport" Member="tblLoginReports" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblLoginReport" />
      <Association Name="tblAdminDetail_tblReplacedBook" Member="tblReplacedBooks" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblReplacedBook" />
      <Association Name="tblAdminDetail_tblTransaction" Member="tblTransactions" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblTransaction" />
    </Type>
  </Table>
  <Table Name="dbo.tblAdminLoginReport" Member="tblAdminLoginReports">
    <Type Name="tblAdminLoginReport">
      <Column Name="LoginID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tblAdminDetail_tblAdminLoginReport" Member="tblAdminDetail" ThisKey="username" OtherKey="AdminUsername" Type="tblAdminDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblAdminTransaction" Member="tblAdminTransactions">
    <Type Name="tblAdminTransaction">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Client" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tblAdminDetail_tblAdminTransaction" Member="tblAdminDetail" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblAdminDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblBookAccounting" Member="tblBookAccountings">
    <Type Name="tblBookAccounting">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="PaymentDue" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="Cash" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="Change" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Association Name="tblAdminDetail_tblBookAccounting" Member="tblAdminDetail" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblAdminDetail" IsForeignKey="true" />
      <Association Name="tblUserDetail_tblBookAccounting" Member="tblUserDetail" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblUserDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblBookPrices" Member="tblBookPrices">
    <Type Name="tblBookPrice">
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Association Name="tblBooksData_tblBookPrice" Member="tblBooksData" ThisKey="Title" OtherKey="Title" Type="tblBooksData" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblBooks" Member="tblBooks">
    <Type Name="tblBook">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateBorrowed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeadline" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActualReturned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsGoodContidion" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IsPaid" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Association Name="tblAdminDetail_tblBook" Member="tblAdminDetail" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblAdminDetail" IsForeignKey="true" />
      <Association Name="tblBooksData_tblBook" Member="tblBooksData" ThisKey="Title" OtherKey="Title" Type="tblBooksData" IsForeignKey="true" />
      <Association Name="tblUserDetail_tblBook" Member="tblUserDetail" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblUserDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblBooksBorrowed" Member="tblBooksBorroweds">
    <Type Name="tblBooksBorrowed">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BorrowersName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateBorrowed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeadline" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tblAdminDetail_tblBooksBorrowed" Member="tblAdminDetail" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblAdminDetail" IsForeignKey="true" />
      <Association Name="tblBooksData_tblBooksBorrowed" Member="tblBooksData" ThisKey="Title" OtherKey="Title" Type="tblBooksData" IsForeignKey="true" />
      <Association Name="tblUserDetail_tblBooksBorrowed" Member="tblUserDetail" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblUserDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblBooksData" Member="tblBooksDatas">
    <Type Name="tblBooksData">
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Author1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Publication_Year" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Field_of_Study" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Association Name="tblBooksData_tblBookPrice" Member="tblBookPrices" ThisKey="Title" OtherKey="Title" Type="tblBookPrice" />
      <Association Name="tblBooksData_tblBook" Member="tblBooks" ThisKey="Title" OtherKey="Title" Type="tblBook" />
      <Association Name="tblBooksData_tblBooksBorrowed" Member="tblBooksBorroweds" ThisKey="Title" OtherKey="Title" Type="tblBooksBorrowed" />
      <Association Name="tblBooksData_tblLostDamagedBook" Member="tblLostDamagedBooks" ThisKey="Title" OtherKey="Title" Type="tblLostDamagedBook" />
      <Association Name="tblBooksData_tblReplacedBook" Member="tblReplacedBooks" ThisKey="Title" OtherKey="Title" Type="tblReplacedBook" />
      <Association Name="tblBooksData_tblTransaction" Member="tblTransactions" ThisKey="Title" OtherKey="Title" Type="tblTransaction" />
    </Type>
  </Table>
  <Table Name="dbo.tblLoginReport" Member="tblLoginReports">
    <Type Name="tblLoginReport">
      <Column Name="LoginID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tblAdminDetail_tblLoginReport" Member="tblAdminDetail" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblAdminDetail" IsForeignKey="true" />
      <Association Name="tblUserDetail_tblLoginReport" Member="tblUserDetail" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblUserDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblLostDamagedBooks" Member="tblLostDamagedBooks">
    <Type Name="tblLostDamagedBook">
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="tblBooksData_tblLostDamagedBook" Member="tblBooksData" ThisKey="Title" OtherKey="Title" Type="tblBooksData" IsForeignKey="true" />
      <Association Name="tblUserDetail_tblLostDamagedBook" Member="tblUserDetail" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblUserDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblReplacedBooks" Member="tblReplacedBooks">
    <Type Name="tblReplacedBook">
      <Column Name="ReplacementID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateReplaced" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tblAdminDetail_tblReplacedBook" Member="tblAdminDetail" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblAdminDetail" IsForeignKey="true" />
      <Association Name="tblBooksData_tblReplacedBook" Member="tblBooksData" ThisKey="Title" OtherKey="Title" Type="tblBooksData" IsForeignKey="true" />
      <Association Name="tblUserDetail_tblReplacedBook" Member="tblUserDetail" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblUserDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblTransaction" Member="tblTransactions">
    <Type Name="tblTransaction">
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tblAdminDetail_tblTransaction" Member="tblAdminDetail" ThisKey="AdminUsername" OtherKey="AdminUsername" Type="tblAdminDetail" IsForeignKey="true" />
      <Association Name="tblBooksData_tblTransaction" Member="tblBooksData" ThisKey="Title" OtherKey="Title" Type="tblBooksData" IsForeignKey="true" />
      <Association Name="tblUserDetail_tblTransaction" Member="tblUserDetail" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblUserDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUserActionReport" Member="tblUserActionReports">
    <Type Name="tblUserActionReport">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tblUserDetail_tblUserActionReport" Member="tblUserDetail" ThisKey="username" OtherKey="UserUsername" Type="tblUserDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblUserDetails" Member="tblUserDetails">
    <Type Name="tblUserDetail">
      <Column Name="GenID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Section" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Grade_Level" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email_Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Question" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Answer" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tblUserDetail_tblUserLoginReport" Member="tblUserLoginReports" ThisKey="UserUsername" OtherKey="username" Type="tblUserLoginReport" />
      <Association Name="tblUserDetail_tblBookAccounting" Member="tblBookAccountings" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblBookAccounting" />
      <Association Name="tblUserDetail_tblBook" Member="tblBooks" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblBook" />
      <Association Name="tblUserDetail_tblBooksBorrowed" Member="tblBooksBorroweds" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblBooksBorrowed" />
      <Association Name="tblUserDetail_tblLoginReport" Member="tblLoginReports" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblLoginReport" />
      <Association Name="tblUserDetail_tblLostDamagedBook" Member="tblLostDamagedBooks" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblLostDamagedBook" />
      <Association Name="tblUserDetail_tblReplacedBook" Member="tblReplacedBooks" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblReplacedBook" />
      <Association Name="tblUserDetail_tblTransaction" Member="tblTransactions" ThisKey="UserUsername" OtherKey="UserUsername" Type="tblTransaction" />
      <Association Name="tblUserDetail_tblUserActionReport" Member="tblUserActionReports" ThisKey="UserUsername" OtherKey="username" Type="tblUserActionReport" />
      <Association Name="tblUserDetail_tblUserReport" Member="tblUserReports" ThisKey="UserUsername" OtherKey="username" Type="tblUserReport" />
    </Type>
  </Table>
  <Table Name="dbo.tblUserReport" Member="tblUserReports">
    <Type Name="tblUserReport">
      <Column Name="transactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="tblUserDetail_tblUserReport" Member="tblUserDetail" ThisKey="username" OtherKey="UserUsername" Type="tblUserDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.AdminUsertype" Method="AdminUsertype">
    <Parameter Name="parameter1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="parameter2" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="AdminUsertypeResult">
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UserUsertype" Method="UserUsertype">
    <Parameter Name="parameter1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="parameter2" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="UserUsertypeResult">
      <Column Name="Userusername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_AdminActionReport" Method="sp_AdminActionReport">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Timestamp" Parameter="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AdminChangePass" Method="sp_AdminChangePass">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AdminChangePassVerify" Method="sp_AdminChangePassVerify">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Security_Question" Parameter="security_Question" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Security_Answer" Parameter="security_Answer" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_AdminChangePassVerifyResult">
      <Column Name="GenID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email_Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Question" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Answer" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_AdminDelete" Method="sp_AdminDelete">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AdminID" Method="sp_AdminID">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AdminInsert" Method="sp_AdminInsert">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="First_Name" Parameter="first_Name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Middle_Name" Parameter="middle_Name" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Last_Name" Parameter="last_Name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Contact_Number" Parameter="contact_Number" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Birthdate" Parameter="birthdate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Age" Parameter="age" Type="System.Int32" DbType="Int" />
    <Parameter Name="Email_Address" Parameter="email_Address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Security_Question" Parameter="security_Question" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Security_Answer" Parameter="security_Answer" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Usertype" Parameter="usertype" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AdminLogin" Method="sp_AdminLogin">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_AdminLoginResult">
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_AdminLoginReport" Method="sp_AdminLoginReport">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Timestamp" Parameter="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="usertype" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AdminTransactionAdd" Method="sp_AdminTransactionAdd">
    <Parameter Name="Attendant" Parameter="attendant" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Client" Parameter="client" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TimeStamp" Parameter="timeStamp" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AdminUpdate" Method="sp_AdminUpdate">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="First_Name" Parameter="first_Name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Middle_Name" Parameter="middle_Name" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Last_Name" Parameter="last_Name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Contact_Number" Parameter="contact_Number" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Birthdate" Parameter="birthdate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Age" Parameter="age" Type="System.Int32" DbType="Int" />
    <Parameter Name="Email_Address" Parameter="email_Address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Security_Question" Parameter="security_Question" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Security_Answer" Parameter="security_Answer" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Usertype" Parameter="usertype" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_AdminUsernameCheck" Method="sp_AdminUsernameCheck">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_AdminUsernameCheckResult">
      <Column Name="GenID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email_Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Question" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Answer" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_BookAction" Method="sp_BookAction">
    <Parameter Name="AdminUsername" Parameter="adminUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserUsername" Parameter="userUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Timestamp" Parameter="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookAdd" Method="sp_BookAdd">
    <Parameter Name="ISBN" Parameter="iSBN" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Author1" Parameter="author1" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Publication_Year" Parameter="publication_Year" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Field_of_Study" Parameter="field_of_Study" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Publisher" Parameter="publisher" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookBorrowing" Method="sp_BookBorrowing">
    <Parameter Name="AdminUsername" Parameter="adminUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserUsername" Parameter="userUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BorrowersName" Parameter="borrowersName" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="DateBorrowed" Parameter="dateBorrowed" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DateDeadline" Parameter="dateDeadline" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookDelete" Method="sp_BookDelete">
    <Parameter Name="BookID" Parameter="bookID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookDuePaid" Method="sp_BookDuePaid">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsPaid" Parameter="isPaid" Type="System.String" DbType="VarChar(2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookEdit" Method="sp_BookEdit">
    <Parameter Name="BookID" Parameter="bookID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ISBN" Parameter="iSBN" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Author1" Parameter="author1" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Publication_Year" Parameter="publication_Year" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Field_of_Study" Parameter="field_of_Study" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Publisher" Parameter="publisher" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="Price" Parameter="price" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookID" Method="sp_BookID">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookPayDue" Method="sp_BookPayDue">
    <Parameter Name="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="adminusername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="userusername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="paymentdue" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="cash" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="change" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookPriceInsert" Method="sp_BookPriceInsert">
    <Parameter Name="title" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="price" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookQuantity" Method="sp_BookQuantity">
    <Parameter Name="title" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="quantity" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookQuantityUpdate" Method="sp_BookQuantityUpdate">
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookReplace" Method="sp_BookReplace">
    <Parameter Name="transactionid" Type="System.Int32" DbType="Int" />
    <Parameter Name="Key" Parameter="key" Type="System.String" DbType="VarChar(2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookReturn" Method="sp_BookReturn">
    <Parameter Name="AdminUsername" Parameter="adminUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserUsername" Parameter="userUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="DateBorrowed" Parameter="dateBorrowed" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DateDeadline" Parameter="dateDeadline" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ActualReturned" Parameter="actualReturned" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IsGoodContidion" Parameter="isGoodContidion" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="IsPaid" Parameter="isPaid" Type="System.String" DbType="VarChar(2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookReturnEdit" Method="sp_BookReturnEdit">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminUsername" Parameter="adminUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserUsername" Parameter="userUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="DateBorrowed" Parameter="dateBorrowed" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DateDeadline" Parameter="dateDeadline" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ActualReturned" Parameter="actualReturned" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IsGoodContidion" Parameter="isGoodContidion" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="IsPaid" Parameter="isPaid" Type="System.String" DbType="VarChar(2)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookReturnEntryDelete" Method="sp_BookReturnEntryDelete">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_BookSearch" Method="sp_BookSearch">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_BookSearchResult">
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Author1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Publication_Year" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Field_of_Study" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_BookView" Method="sp_BookView">
    <ElementType Name="sp_BookViewResult">
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Author1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Publication_Year" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Field_of_Study" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_DeleteDamagedBooks" Method="sp_DeleteDamagedBooks">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteUser" Method="sp_DeleteUser">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertDamagedBooks" Method="sp_InsertDamagedBooks">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertUserAction" Method="sp_InsertUserAction">
    <Parameter Name="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_LoginReport" Method="sp_LoginReport">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="AdminUsername" Parameter="adminUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserUsername" Parameter="userUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Timestamp" Parameter="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="usertype" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ReplaceBook" Method="sp_ReplaceBook">
    <Parameter Name="UserUsername" Parameter="userUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="AdminUsername" Parameter="adminUsername" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DateReplaced" Parameter="dateReplaced" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SearchAccountingNotPaid" Method="sp_SearchAccountingNotPaid">
    <Parameter Name="searchkey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_SearchAccountingNotPaidResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateBorrowed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeadline" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActualReturned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsGoodContidion" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Ispaid" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SearchBorrowedBooks" Method="sp_SearchBorrowedBooks">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_SearchBorrowedBooksResult">
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateBorrowed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeadline" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SearchUserModified" Method="sp_SearchUserModified">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_SearchUserModifiedResult">
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserActionReport" Method="sp_UserActionReport">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Timestamp" Parameter="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserChangePass" Method="sp_UserChangePass">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserChangePassVerify" Method="sp_UserChangePassVerify">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Security_Question" Parameter="security_Question" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Security_Answer" Parameter="security_Answer" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_UserChangePassVerifyResult">
      <Column Name="GenID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Section" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Grade_Level" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email_Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Question" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Answer" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserID" Method="sp_UserID">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserInsert" Method="sp_UserInsert">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="First_Name" Parameter="first_Name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Middle_Name" Parameter="middle_Name" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Last_Name" Parameter="last_Name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Contact_Number" Parameter="contact_Number" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Birthdate" Parameter="birthdate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Age" Parameter="age" Type="System.Int32" DbType="Int" />
    <Parameter Name="Section" Parameter="section" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Grade_Level" Parameter="grade_Level" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Email_Address" Parameter="email_Address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Security_Question" Parameter="security_Question" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Security_Answer" Parameter="security_Answer" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Usertype" Parameter="usertype" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserLogin" Method="sp_UserLogin">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="sp_UserLoginResult">
      <Column Name="Userusername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserLoginReport" Method="sp_UserLoginReport">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Timestamp" Parameter="timestamp" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="usertype" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserSearch" Method="sp_UserSearch">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_UserSearchResult">
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Section" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Grade_Level" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email_Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserUpdate" Method="sp_UserUpdate">
    <Parameter Name="ID" Parameter="iD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="First_Name" Parameter="first_Name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Middle_Name" Parameter="middle_Name" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Last_Name" Parameter="last_Name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Contact_Number" Parameter="contact_Number" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Birthdate" Parameter="birthdate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Age" Parameter="age" Type="System.Int32" DbType="Int" />
    <Parameter Name="Section" Parameter="section" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Grade_Level" Parameter="grade_Level" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Email_Address" Parameter="email_Address" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Security_Question" Parameter="security_Question" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Security_Answer" Parameter="security_Answer" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Usertype" Parameter="usertype" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UserUsernameCheck" Method="sp_UserUsernameCheck">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_UserUsernameCheckResult">
      <Column Name="GenID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Section" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Grade_Level" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email_Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Question" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Answer" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserView" Method="sp_UserView">
    <ElementType Name="sp_UserViewResult">
      <Column Name="GenID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Contact_Number" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Section" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Grade_Level" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email_Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Question" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Security_Answer" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Usertype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewAccounting" Method="sp_ViewAccounting">
    <ElementType Name="sp_ViewAccountingResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="PaymentDue" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="Cash" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="Change" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewBorrowedBooks" Method="sp_ViewBorrowedBooks">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_ViewBorrowedBooksResult">
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateBorrowed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeadline" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewBorrowedBooksAdmin" Method="sp_ViewBorrowedBooksAdmin">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_ViewBorrowedBooksAdminResult">
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateBorrowed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeadline" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewLostBooks" Method="sp_ViewLostBooks">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_ViewLostBooksResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IsGoodContidion" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IsPaid" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewLostBooksTable" Method="sp_ViewLostBooksTable">
    <Parameter Name="SearchKey" Parameter="searchKey" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_ViewLostBooksTableResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IsGoodContidion" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IsPaid" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewNotPaidBooks" Method="sp_ViewNotPaidBooks">
    <ElementType Name="sp_ViewNotPaidBooksResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateBorrowed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeadline" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActualReturned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsGoodContidion" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="IsPaid" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewTopay" Method="sp_ViewTopay">
    <ElementType Name="sp_ViewTopayResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DateBorrowed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeadline" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActualReturned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsGoodContidion" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Ispaid" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ViewUserModified" Method="sp_ViewUserModified">
    <ElementType Name="sp_ViewUserModifiedResult">
      <Column Name="UserUsername" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middle_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>